cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #3e2d16
selection_background  #ddc2a1
url_color             #ffb950

color0   #131313
color1   #ff4c3e
color2   #6bff50
color3   #ffde3e
color4   #f2a22a
color5   #764600
color6   #ffb950
color7   #fff6ea
color8   #a59e94
color9   #ff857b
color10  #97ff84
color11  #ffea84
color12  #ffc36a
color13  #ffce84
color14  #ffdfb0
color15  #fffbf6
