cursor #e0e2e6
cursor_text_color #c0c7cf

foreground            #e0e2e6
background            #101417
selection_foreground  #1a3344
selection_background  #b0cadf
url_color             #89ceff

color0   #101417
color1   #ff729e
color2   #7fff8f
color3   #fff772
color4   #6bbaf2
color5   #114c76
color6   #89ceff
color7   #eff8ff
color8   #99a0a5
color9   #ff9fbd
color10  #a5ffb0
color11  #fff9a5
color12  #9ad5ff
color13  #acdcff
color14  #c9e8ff
color15  #f8fcff
