#!/bin/bash

INTERNAL_DISPLAY="LVDS-1"
EXTERNAL_DISPLAY=$(hyprctl monitors | grep "HDMI" | awk '{print $1}')

# Check if HDMI is connected
if [ -z "$EXTERNAL_DISPLAY" ]; then
  notify-send "No external display detected!"
  exit 1
fi

# Rofi menu options
MODE=$(echo -e "Internal Only\nMirror\nExtend\nProject\nDisconnect" | rofi -dmenu -p "Display Mode")

case "$MODE" in
"Internal Only")
  hyprctl --batch "keyword monitor $INTERNAL_DISPLAY,preferred,0x0,1 ; keyword monitor $EXTERNAL_DISPLAY,disable"
  ;;
"Mirror")
  hyprctl --batch "keyword monitor $INTERNAL_DISPLAY,preferred,0x0,1 ; keyword monitor $EXTERNAL_DISPLAY,preferred,0x0,1,mirror,$INTERNAL_DISPLAY"
  ;;
"Extend")
  hyprctl --batch "keyword monitor $INTERNAL_DISPLAY,preferred,0x0,1 ; keyword monitor $EXTERNAL_DISPLAY,preferred,1920x0,1"
  ;;
"Project")
  hyprctl --batch "keyword monitor $INTERNAL_DISPLAY,disable ; keyword monitor $EXTERNAL_DISPLAY,preferred,0x0,1"
  ;;
"Disconnect")
  hyprctl --batch "keyword monitor $EXTERNAL_DISPLAY,disable ; keyword monitor $INTERNAL_DISPLAY,preferred,0x0,1"
  ;;
*)
  exit 0
  ;;
esac

notify-send "Display mode set to: $MODE"
