general.live_config_reload = true
working_directory = "None"

# Themes --
general.import = [ 
  "~/.cache/wal/colors-alacritty.toml",
]

[window]
title = "Alacritty"
decorations = "none"
opacity = 0.9
padding.x = 0
padding.y = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font Propo"
normal.style = "Regular"
size = 11.5
