# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules


#####################
## Floating windows
#####################
# blueman-manager
windowrule {
    name = blueman-float
    match:class = blueman-manager
    # match:class = blueman-services

    float = on
    size = 320 320
}
# file manager operations
# windowrule {
#     name = file-manager-floating
#     match:title = (?i).*Removable.*
#     match:title = (?i).*File Operation Progress.*
#     match:title = (?i).*directory.*
#     match:title = (?i).*Select.*
#     match:title = (?i).*Choose.*
#     match:title = (?i).*Rename.*
#     match:title = (?i).*Select Folder.*
#
#     float = on
# }
# Vivaldi Settings
# windowrule = float, title:^(Vivaldi Settings: .+ - Vivaldi)$
# windowrule = center (1), title:^(Vivaldi Settings: .+ - Vivaldi)$
# windowrule = size 1024 600, title:^(Vivaldi Settings: .+ - Vivaldi)$
# # Xarchiver
# windowrule = float, class:xarchiver
# windowrule = size 900 600, class:xarchiver
# # File Roller
# windowrule = float, class:org.gnome.FileRoller
# windowrule = size 900 600, class:org.gnome.FileRoller
# # Zenity
# windowrule = float, class:zenity
# windowrule = size 900 550, class:zenity
# # xdg-portal
# windowrule = float, class:xdg-desktop-portal-gtk
# windowrule = size 900 550, class:xdg-desktop-portal-gtk
# # gnome-calculator
# windowrule = float, class:org.gnome.Calculator

#####################
## Tiling
#####################
# windowrule = tile,initialTitle:^(Godot)$,initialClass:^(Godot)$
# windowrule = float,title:^((.*)(DEBUG)),initialClass:^(Godot)$,initialTitle:^(.*)(DEBUG)(.*)$,class:^(Godot)$

#####################
# Workspace Specific Apps
#####################
# WEB
# windowrulev2 = workspace 1, class:^(vivaldi.*)
# windowrulev2 = workspace 1, class:fdm
# # DEV
# windowrulev2 = workspace 2, class:kitty
# windowrulev2 = workspace 2, title:zellij
# windowrulev2 = workspace 2, class:Code
# windowrulev2 = workspace 2, class:Postman
# # FILES/DOCS
# windowrulev2 = workspace 3, class:thunar
# windowrulev2 = workspace 3, class:org.gnome.Nautilus
# windowrulev2 = workspace 3, class:org.gnome.Loupe
# windowrulev2 = workspace 3, class:org.localsend.localsend_app
# windowrulev2 = workspace 3, class:^(libreoffice.*)
# # MEDIA
# windowrulev2 = workspace 4, class:com.github.iwalton3.jellyfin-media-player
# windowrulev2 = workspace 4, class:mpv
# windowrulev2 = workspace 4, class:vlc
# windowrulev2 = workspace 4, title:rmpc
# windowrulev2 = workspace 4, class:org.musicbrainz.Picard
# windowrulev2 = workspace 4, class:Spotify
# # COMMUNICATION
# windowrulev2 = workspace 5, class:org.telegram.desktop
# windowrulev2 = workspace 5, class:zoom
# windowrulev2 = workspace 5, class:teams-for-linux
# # GAMING
# # windowrulev2 = workspace 6, class:steam
# windowrulev2 = workspace 6, class:net.lutris.Lutris
# windowrulev2 = workspace 6, class:heroic
# windowrulev2 = workspace 6, class:com.vysp3r.ProtonPlus
# # TOOLS/MISC
# windowrulev2 = workspace 7, class:YACReaderLibrary
# windowrulev2 = workspace 7, class:YACReader
# windowrulev2 = workspace 7, class:virt-manager
# windowrulev2 = workspace 7, class:org.gnome.Boxes
# windowrulev2 = workspace 7, class:comictagger
# windowrulev2 = workspace 7, class:org.qbittorrent.qBittorrent
# windowrulev2 = workspace 7, class:org.keepassxc.KeePassXC

#####################
## Misc
#####################
# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
